sudo: required
services:
  - docker

before_install:
  - docker build -t ligain/docker-react -f Dockerfile.dev .

script:
  - docker run ligain/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-eu-west-1-169254310775"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

